apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-d3io
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-d3io
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-hello-worlhwn6
  namespace: psturc-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: devfile-sample-hello-world-d3io
    weight: 100
status: {}
