apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-d3io
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-d3io
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-hello-world-d3io
  namespace: psturc-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: devfile-sample-hello-world-d3io
status:
  loadBalancer: {}
